<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.aimluck.eip</groupId>
  <artifactId>aipo</artifactId>
  <version>8.1.1</version>
  <packaging>pom</packaging>
  <modules>
  	<module>aipo-core</module>
  	<module>aipo-jetspeed</module>
  	<module>aipo-oms</module>
  	<module>aipo-lib-accessctl</module>
  	<module>aipo-lib-addressbookuser</module>
  	<module>aipo-lib-category</module>
  	<module>aipo-lib-config</module>
  	<module>aipo-lib-eventlog</module>
  	<module>aipo-lib-facility</module>
  	<module>aipo-lib-mail</module>
  	<module>aipo-lib-portal</module>
  	<module>aipo-lib-social</module>
  	<module>aipo-lib-storage</module>
  	<module>aipo-lib-user</module>
  	<module>aipo-lib-userfacility</module>
  </modules>
</project>