

package org.apache.jetspeed.om.security.turbine;

import java.util.List;

import org.apache.torque.TorqueException;

/**
 * This class manages TurbineRolePermission objects.
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Jun 10 23:17:32 JST 2004]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public class TurbineRolePermissionManager
    extends BaseTurbineRolePermissionManager
{
    /**
     * Creates a new <code>TurbineRolePermissionManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public TurbineRolePermissionManager()
        throws TorqueException
    {
        super();
    }

    /**
     * Gets a list of ModuleEntities based on id's.
     *
     * @param moduleIds a <code>NumberKey[]</code> value
     * @return a <code>List</code> value
     * @exception TorqueException if an error occurs
     */
    @SuppressWarnings({ "rawtypes", "unchecked" })
    @Override
    protected List retrieveStoredOMs(List ids)
        throws TorqueException
    {
        return TurbineUserPeer.retrieveByPKs(ids);
    }
}
